name: Deploy Vue.js Calculator to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Debug - List directory contents
        run: |
          pwd
          ls -la
      
      - name: Install dependencies
        working-directory: ./vue-calculator  # Adjust this path based on your repository structure
        run: npm install
      
      - name: Build the application
        working-directory: ./vue-calculator  # Same path as above
        run: npm run build
      
      - name: Deploy to production via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "vue-calculator/dist/"  # Adjust based on where your dist folder is
          target: "/vue-calculator/"
          strip_components: 1  # This will strip the vue-calculator part from the path
          rm: true