name: Deploy Nuxt Calculator to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Debug - List directory contents
        run: |
          pwd
          ls -la
      
      - name: Install dependencies
        working-directory: ./vue-calculator
        run: nvm install -g n
      
      - name: Build the application
        working-directory: ./vue-calculator
        run: npm run build
      
      - name: Export static site
        working-directory: ./vue-calculator
        run: npm run generate
      
      - name: Deploy to production via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "/vue-calculator/.output/public/"
          target: "/vue-calculator/nuxt-calculator/"
          strip_components: 1
          rm: true
